#!/usr/bin/env python3
"""Generate the P08 vision simulation assets (deterministic; committed).

    scripts/make_vision_assets.py [--check]

Writes, under src/reef_sim/:
  models/reef_vision_scene/            textured wall, plain (weak-texture) wall,
                                       plain floor patch, red target sphere
    materials/textures/texture_rich.png   procedural texture (seeded), our own
  models/reef_x3_rgbd/model.sdf        reef_x3 + a forward-looking rgbd_camera
  worlds/x3_vision.sdf                 x3_flight + Sensors (ogre2) + scene,
                                       stock truth-fed controller (open loop)
  worlds/x3_closed_loop_vision.sdf     x3_closed_loop + Sensors + scene
With --check, compares instead of writing (exit 1 if anything differs).
PNGs are written by a minimal encoder (zlib, no metadata) so the bytes do
not depend on library versions. See docs/VISION.md section 5.
"""
import random
import struct
import sys
import zlib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SIM = ROOT / 'src' / 'reef_sim'

# Camera profile (USER, 2026-10-01): 320x240 at 15 Hz; fallback 160x120 at 10 Hz.
CAMERA = dict(width=320, height=240, rate=15, hfov=1.0471975511965976, near=0.3, far=8.0)
# Mounting: kiwi's position (rgbd_to_velocity b7637198 params/kiwi_camera.yaml,
# body_to_camera_trans, FRD) with an ideal forward orientation; in the
# converter's convention that is body_to_camera_quat = (0.5, -0.5, 0.5, -0.5).
MOUNT_FRD = (0.1354765750332004, 0.0175314092839309, -0.0455417178618858)
MOUNT_QUAT = (0.5, -0.5, 0.5, -0.5)
# Scene (world ENU; the X3 starts at the origin facing +x).
WALL_X = 4.0
RICH_Y = (-3.0, 1.5)
PLAIN_Y = (1.5, 6.0)
WALL_Z = (0.0, 3.0)
TARGET = (3.5, -1.0, 1.4)
TARGET_RADIUS = 0.08


def png(path, rgb_rows, width, height):
    raw = b''.join(b'\x00' + bytes(row) for row in rgb_rows)

    def chunk(tag, data):
        return struct.pack('>I', len(data)) + tag + data + struct.pack('>I', zlib.crc32(tag + data) & 0xffffffff)
    data = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0)) + \
        chunk(b'IDAT', zlib.compress(raw, 9)) + chunk(b'IEND', b'')
    return path, data


def rich_texture(n=512, seed=8):
    """Multi-scale random blocks and dots: many well-separated corners."""
    rng = random.Random(seed)
    img = [[[128, 128, 128] for _ in range(n)] for _ in range(n)]
    for size, count in ((96, 30), (48, 120), (24, 400), (10, 1500)):
        for _ in range(count):
            x0, y0 = rng.randrange(n), rng.randrange(n)
            c = [rng.randrange(256) for _ in range(3)]
            for y in range(y0, min(n, y0 + size)):
                for x in range(x0, min(n, x0 + size)):
                    img[y][x] = c
    rows = [[v for px in row for v in px] for row in img]
    return rows, n


def box(name, center, size, color=None, texture=None, collide=True):
    cx, cy, cz = center
    sx, sy, sz = size
    mat = (f'<material><diffuse>{color} 1</diffuse><ambient>{color} 1</ambient></material>' if color else
           f'<material><diffuse>1 1 1 1</diffuse><pbr><metal><albedo_map>{texture}</albedo_map></metal></pbr></material>')
    col = (f'<collision name="{name}_collision"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry></collision>'
           if collide else '')
    return (f'      <link name="{name}"><pose>{cx} {cy} {cz} 0 0 0</pose>{col}'
            f'<visual name="{name}_visual"><geometry><box><size>{sx} {sy} {sz}</size></box></geometry>{mat}</visual></link>')


def scene_model():
    t = 'model://reef_vision_scene/materials/textures/texture_rich.png'
    zc, zh = (WALL_Z[0] + WALL_Z[1]) / 2, WALL_Z[1] - WALL_Z[0]
    links = [
        box('wall_rich', (WALL_X + 0.05, (RICH_Y[0] + RICH_Y[1]) / 2, zc), (0.1, RICH_Y[1] - RICH_Y[0], zh), texture=t),
        box('wall_plain', (WALL_X + 0.05, (PLAIN_Y[0] + PLAIN_Y[1]) / 2, zc), (0.1, PLAIN_Y[1] - PLAIN_Y[0], zh),
            color='0.55 0.55 0.55'),
    ]
    sphere = (f'      <link name="target"><pose>{TARGET[0]} {TARGET[1]} {TARGET[2]} 0 0 0</pose>'
              f'<visual name="target_visual"><geometry><sphere><radius>{TARGET_RADIUS}</radius></sphere></geometry>'
              '<material><diffuse>1 0 0 1</diffuse><ambient>1 0 0 1</ambient><emissive>1 0 0 1</emissive></material>'
              '</visual></link>')
    return f'''<?xml version="1.0"?>
<!-- GENERATED by scripts/make_vision_assets.py (P08). Our own scene, no third-party content:
     a richly textured wall (procedural texture), a plain wall of the same depth (weak texture),
     and a red target sphere for the camera projection check (docs/VISION.md section 5). -->
<sdf version="1.9">
  <model name="reef_vision_scene">
    <static>true</static>
{chr(10).join(links)}
{sphere}
  </model>
</sdf>
'''


def x3_rgbd_model():
    src = (SIM / 'models' / 'reef_x3' / 'model.sdf').read_text()
    x, y, z = MOUNT_FRD
    c = CAMERA
    sensor = f'''      <!-- RGB-D camera (P08, GENERATED by scripts/make_vision_assets.py): forward-looking, at the
           legacy kiwi position (FRD {x:.4f} {y:.4f} {z:.4f} m = FLU {x:.4f} {-y:.4f} {-z:.4f} m), ideal
           orientation (Gazebo camera x = body forward). Converter extrinsics: body_to_camera_quat
           {MOUNT_QUAT}, body_to_camera_trans {MOUNT_FRD}. -->
      <sensor name='rgbd' type='rgbd_camera'>
        <pose>{x} {-y} {-z} 0 0 0</pose>
        <always_on>1</always_on>
        <update_rate>{c["rate"]}</update_rate>
        <topic>/reef/x3/rgbd</topic>
        <gz_frame_id>x3/camera_optical</gz_frame_id>
        <camera>
          <horizontal_fov>{c["hfov"]}</horizontal_fov>
          <image><width>{c["width"]}</width><height>{c["height"]}</height><format>R8G8B8</format></image>
          <clip><near>{c["near"]}</near><far>{c["far"]}</far></clip>
          <depth_camera><clip><near>{c["near"]}</near><far>{c["far"]}</far></clip></depth_camera>
        </camera>
      </sensor>
'''
    anchor = "    </link>\n    <link name='X3/rotor_0'>"
    assert src.count(anchor) == 1
    out = src.replace(anchor, sensor + anchor)
    out = out.replace("<model name='reef_x3'>", "<model name='reef_x3_rgbd'>")
    return out.replace('<!--\n  reef_x3:', '<!--\n  reef_x3_rgbd: GENERATED from reef_x3/model.sdf by scripts/make_vision_assets.py\n  (P08): the same vehicle plus a forward-looking RGB-D camera.\n\n  reef_x3:', 1)


def vision_world(base_name, new_name):
    src = (SIM / 'worlds' / base_name).read_text()
    sensors = ('    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">'
               '<render_engine>ogre2</render_engine></plugin>\n')
    anchor = '    <plugin filename="gz-sim-imu-system" name="gz::sim::systems::Imu"/>\n'
    assert src.count(anchor) == 1
    out = src.replace(anchor, anchor + sensors)
    out = out.replace('<uri>model://reef_x3</uri>', '<uri>model://reef_x3_rgbd</uri>')
    scene = ('    <include>\n      <name>vision_scene</name>\n      <uri>model://reef_vision_scene</uri>\n'
             '    </include>\n\n    <include>\n      <name>x3</name>')
    anchor = '    <include>\n      <name>x3</name>'
    assert out.count(anchor) == 1
    out = out.replace(anchor, scene)
    wname = new_name.replace('.sdf', '')
    out = out.replace(f'<world name="{base_name.replace(".sdf", "")}">', f'<world name="{wname}">')
    header = (f'<?xml version="1.0" ?>\n<!--\n  {wname}: GENERATED from {base_name} by scripts/make_vision_assets.py (P08):\n'
              '  the same world plus the Sensors system (ogre2 rendering, run with --headless-rendering),\n'
              '  the X3 with an RGB-D camera (reef_x3_rgbd), and the vision scene (reef_vision_scene).\n-->\n')
    return header + out.split('?>', 1)[1].lstrip('\n')


def outputs():
    rows, n = rich_texture()
    tex = SIM / 'models' / 'reef_vision_scene' / 'materials' / 'textures' / 'texture_rich.png'
    files = dict([png(tex, rows, n, n)])
    files[SIM / 'models' / 'reef_vision_scene' / 'model.sdf'] = scene_model().encode()
    files[SIM / 'models' / 'reef_vision_scene' / 'model.config'] = (
        '<?xml version="1.0"?>\n<model><name>reef_vision_scene</name><version>1.0</version>'
        '<sdf version="1.9">model.sdf</sdf><description>P08 vision test scene (generated, own content)'
        '</description></model>\n').encode()
    files[SIM / 'models' / 'reef_x3_rgbd' / 'model.sdf'] = x3_rgbd_model().encode()
    files[SIM / 'models' / 'reef_x3_rgbd' / 'model.config'] = (
        (SIM / 'models' / 'reef_x3' / 'model.config').read_text().replace('<name>reef_x3</name>', '<name>reef_x3_rgbd</name>')
        .replace('with an added IMU', 'with an added IMU and RGB-D camera (P08, generated)')).encode()
    files[SIM / 'worlds' / 'x3_vision.sdf'] = vision_world('x3_flight.sdf', 'x3_vision.sdf').encode()
    files[SIM / 'worlds' / 'x3_closed_loop_vision.sdf'] = vision_world('x3_closed_loop.sdf', 'x3_closed_loop_vision.sdf').encode()
    return files


def main(argv):
    check = '--check' in argv
    bad = []
    for path, data in outputs().items():
        if check:
            if not path.exists() or path.read_bytes() != data:
                bad.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
            print(f'wrote {path.relative_to(ROOT)} ({len(data)} bytes)')
    if check:
        print('vision assets up to date' if not bad else 'OUT OF DATE: ' + ', '.join(bad))
        return 1 if bad else 0
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
